# Generated by Django 4.2.5 on 2023-11-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='surname',
        ),
        migrations.AlterField(
            model_name='advuser',
            name='name',
            field=models.CharField(max_length=254, verbose_name='ФИО'),
        ),
    ]
