# Generated by Django 4.2.5 on 2023-11-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=21, unique=True, verbose_name='Категория'),
        ),
    ]
