# Generated by Django 4.2.5 on 2023-11-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, choices=[('bigApartment', 'bigApartment'), ('Medium-sizedApartment', 'Medium-sizedApartment'), ('smallApartment', 'smallApartment')], default='a', max_length=21, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Новая', 'Новая'), ('Принято в работу', 'Принято в работу'), ('Выполнено', 'Выполнено')], default='Новая', max_length=16, verbose_name='Статус'),
        ),
    ]
